CREATE TABLE IF NOT EXISTS "task_board" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text not null,
  "description" text default null,
  "created_at" timestamp not null,
  "updated_at" timestamp not null
);