CREATE TABLE IF NOT EXISTS "task" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text not null,
  "description" text default null,
  "sub_tasks" int[] not null,
  "task_list_id" int not null,
  "created_at" timestamp not null,
  "updated_at" timestamp not null,
  constraint "fk_task_task_list"
    foreign key ("task_list_id")
    references "task_list" ("id")
); 