CREATE TABLE IF NOT EXISTS "task_board" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text not null,
  "description" text default null,
  "created_at" timestamp not null,
  "updated_at" timestamp not null
);

ALTER TABLE "task_list" ADD COLUMN IF NOT EXISTS "task_board_id" int not null;

ALTER TABLE "task_list" DROP CONSTRAINT IF EXISTS "task_board_task_list_fk";
ALTER TABLE "task_list" ADD CONSTRAINT "task_board_task_list_fk" FOREIGN KEY ("task_board_id") REFERENCES "task_board"("id");  